import { gallery1, gallery2, gallery3, gallery4, image } from "./graphic/images.js";

export const dataProduct = [
  {
    id: 1,
    title: "Organic Carrots",
    price: "25000",
    amountPerSell: 1,
    unit: "kg",
    desc: "Fresh, crunchy, and naturally grown carrots packed with nutrients.",
    category: "Vegetables",
    featured: false,
    image: gallery1,
    link: "https://youtube.com",
  },
  {
    id: 2,
    title: "Farm Fresh Eggs",
    price: "40000",
    amountPerSell: 12,
    unit: "pieces",
    desc: "Free-range eggs, rich in protein and omega-3, straight from our farm.",
    category: ["Dairy & Eggs", "Protein"],
    featured: true,
    image: gallery2,
    link: "https://youtube.com",
  },
  {
    id: 3,
    title: "Organic Tomatoes",
    price: "30000",
    amountPerSell: 1,
    unit: "kg",
    desc: "Juicy, vine-ripened organic tomatoes, perfect for salads and cooking.",
    category: "Vegetables",
    featured: true,
    image: gallery3,
    link: "https://youtube.com",
  },
  {
    id: 4,
    title: "Raw Honey",
    price: "75000",
    amountPerSell: 500,
    unit: "ml",
    desc: "Pure, unprocessed honey with natural antioxidants and enzymes.",
    category: ["Natural Sweeteners", "Health Products"],
    featured: true,
    image: gallery4,
    link: "https://youtube.com",
  },
  {
    id: 5,
    title: "Organic Spinach",
    price: "28000",
    amountPerSell: 1,
    unit: "kg",
    desc: "Fresh, pesticide-free spinach, rich in vitamins and minerals.",
    category: ["Vegetables", "Leafy Greens"],
    featured: false,
    image: gallery1,
    link: "https://youtube.com",
  },
  {
    id: 6,
    title: "Whole Wheat Bread",
    price: "35000",
    amountPerSell: 1,
    unit: "loaf",
    desc: "Freshly baked whole wheat bread made with organic ingredients.",
    category: ["Bakery", "Healthy Snacks"],
    featured: true,
    image: gallery2,
    link: "https://youtube.com",
  },
  {
    id: 7,
    title: "Almond Milk",
    price: "55000",
    amountPerSell: 1,
    unit: "liter",
    desc: "Nutritious, dairy-free almond milk made from organic almonds.",
    category: ["Dairy Alternatives", "Beverages"],
    featured: false,
    image: gallery3,
    link: "https://youtube.com",
  },
  {
    id: 8,
    title: "Organic Avocados",
    price: "60000",
    amountPerSell: 1,
    unit: "kg",
    desc: "Creamy, nutrient-dense organic avocados perfect for healthy meals.",
    category: ["Fruits", "Superfoods"],
    featured: true,
    image: gallery4,
    link: "https://youtube.com",
  },
];

